### ISSUE TITLE
The item system is horrible.

### ISSUE THREAD

**Issue by ArikSquad** [Nimaari/VehiclesRepairConsumableAddon#1] opened 2023-09-11 19:02 UTC
I can use my anvil to rename items to the name, then it will work as it would. I would suggest using something like PersistentDataContainers. Current way is no way near secure.

**Comment by Nimaari** [comment] 2023-09-12 12:02
You can change the string in the configuration file to something that cannot be named with an anvil, such as using a colorcode or something of the sort.  As such - the contains method would not return true.  The current system was made like this for simplicity's sake, rather than relying on the plugin for managing the special item.  If you do not like the solution above, then I will look into considering a more advanced solution.

**Comment by Nimaari** [comment] 2023-09-12 12:05
Additionally, if you are wondering how you are supposed to get the item then without an anvil... (if you have a colorcode set)

Essentials -> `/give Nimaari golden_pickaxe name:&eRepair_Tool`
Vanilla -> `/give Nimaari golden_pickaxe{display:{Name:'[{"text":"Repair Tool","color":"yellow"}]'}} 1`

**Comment by ArikSquad** [comment] 2023-09-15 16:54
> Additionally, if you are wondering how you are supposed to get the item then without an anvil... (if you have a colorcode set)
> 
> Essentials -> `/give Nimaari golden_pickaxe name:&eRepair_Tool` Vanilla -> `/give Nimaari golden_pickaxe{display:{Name:'[{"text":"Repair Tool","color":"yellow"}]'}} 1`

I'm not wondering that



> You can change the string in the configuration file to something that cannot be named with an anvil, such as using a colorcode or something of the sort. As such - the contains method would not return true. The current system was made like this for simplicity's sake, rather than relying on the plugin for managing the special item. If you do not like the solution above, then I will look into considering a more advanced solution.

That's still really unsecure. The persistent data container is really simple. See this: <https://docs.papermc.io/paper/dev/pdc> (it's a papermc doc page but it's a spigot thing too) You can have the key as itemType and then have the string as repairItem and all

**Comment by Nimaari** [comment] 2024-05-31 07:28
I still don't see a need to utilize PersistentDataContainers for such a simple plugin. I have been using these method(s) for my own server(s) and I have not had a single incident for ~4 years that I've been using them. If we were managing multiple custom items alike ItemsAdder or Oraxen, then I would understand. If severe issues are caused by this, which they are not as of now, then I will reconsider.  Thank you for your feedback, I will be closing this now.

**Closed as completed by Nimaari** 2024-05-31 07:28 UTC
